### ISSUE TITLE
build HelloTriangle project failed in vs2015

### ISSUE THREAD

**Issue by LarryMai** [microsoft/angle#59] opened 2016-03-26 03:08 UTC
![screenshot 74](https://cloud.githubusercontent.com/assets/3214309/14057665/56cc3468-f342-11e5-9040-2aaf88daeee7.png)
1. open File->New->Project->templates->8.1->win32->Win32 Application for OPENGL ES 
2. build failed and get compile error LNK1104 can't open file 'libcpmtd.lib;

**Comment by LarryMai** [comment] 2016-03-26 03:11
Another question :　Can I use ANGLE to combine OPENGL Interface with mediafoundation transform?
thx

**Comment by austinkinross** [comment] 2016-03-29 15:54
Hi, the Win32 template was designed for Visual Studio 2013. On the left hand side of you screenshot, you can see that it says that your project is called "ApplicationForOpenGLES1 (Visual Studio 2013)". If you right click there and click "Upgrade VC++ Compiler and Libraries", then your project will be updated for VS2015 and it should compile successfully.

Regarding OpenGL/MediaFoundation interop, yes this is possible using interop between D3D devices. We don't have any MF samples to share with you, but if you can get your MF content onto a shared D3D surface then you can use the techniques described in this Wiki article to share its contents with OpenGL ES rendering in ANGLE: https://github.com/MSOpenTech/angle/wiki/Interop-with-other-DirectX-code

Let me know if you have any more questions,
Austin

**Comment by austinkinross** [comment] 2016-04-21 19:44
Hi, I'm closing this issue since I believe your questions have been answered. Feel free to reopen this if you're still having problems!

**Closed as completed by austinkinross** 2016-04-21 19:44 UTC
