### ISSUE TITLE
NuGet not working

### ISSUE THREAD

**Issue by Gerharddc** [microsoft/angle#43] opened 2015-08-02 06:39 UTC
It does not appear as if though the NuGet package is working for runtime components. If I try to call a function from a C++ runtime component using the NuGet package in C# then I immediately get a file not found ("The specified module could not be found. (Exception from HRESULT: 0x8007007E)") exception when invoking the function. This appears to be exactly the same as an error that I used to get with the manual compiled angle binaries when I had not set up VS to use different binaries for different build configurations.

**Comment by Gerharddc** [comment] 2015-08-02 09:16
Ok sorry, the problem it appears is actually that the DLLs which are now in the C++ are not being copied into the root directory anymore. The only way to resolve this at the moment is to add the DLLs to the C# project. Would there be a more elegant way to do this with NuGet?

**Comment by austinkinross** [comment] 2015-08-03 19:43
Hi, thanks a lot for reporting this! I've reproduced the issue but it isn't immediately clear where the problem lies. We'll continue to investigate.

For now, I can't find a more elegant solution than adding the DLLs to the C# project as you suggest, so I recommend continuing to do that. We'll let you know if/when we find a better solution.

Thanks again,
Austin

**Comment by Gerharddc** [comment] 2015-08-04 12:57
@austinkinross Thanks, maybe this is more of a fundamental flaw with the way Visual Studio handles DLLs in C++ projects?

**Comment by jglanfield** [comment] 2015-09-24 14:33
I've had the exact same issue. I got it working by editing the csproj file to copy in the correct version of the DLL (e.g., x64) as needed. However, as soon as I jumped to another machine and pulled the latest from the git repo, although the DLL is still being copied to Core/ at build, the app still crashes when trying to load the DLL. TL;DR: NuGet is a huge pain. ;)

**Comment by jglanfield** [comment] 2015-09-24 15:02
Sorry, my bad. I was copying the wrong version of the DLLs to the project :(

**Comment by jglanfield** [comment] 2015-09-24 15:15
Any suggestions as to how to remove the additional DLLs that are copied to bin/ during the build process? For example, the C++ project will have the DLLs in $(OutDir)\Core\CPPProjectName

But since the app can't find them (and hence the need for the additional copy to the root directory), we now have an extra set of DLLs being added to the app that aren't needed. A post build event doesn't seem to work either.

**Comment by austinkinross** [comment] 2015-10-16 19:53
Hi all, thanks for reporting this issue! It is now fixed in version 2.1.5 of our NuGet package, available here: https://www.nuget.org/packages/ANGLE.WindowsStore/

**Closed as completed by austinkinross** 2015-10-16 19:53 UTC
