### ISSUE TITLE
SwapChainPanel doesn't resize

### ISSUE THREAD

**Issue by mgrviper** [microsoft/angle#123] opened 2017-05-16 07:57 UTC
On desktop sometimes after resizing* UWP app (and changing Window::Current->Content from game to splash and back) SwapChainPanel stops resizing completely till change of Window::Current->Content to another view. Window itself is resizing alright. 

SwapChainPanelSizeChangedHandler from SwapChainPanelNativeWindow.h stop receiving events till change of view. 
In game i still can receive SizeChanged event for CoreWindow, but not for SwapChainPanel.

*panel resizes with significant delay after window, possible reproduction of https://github.com/Microsoft/angle/issues/70 and/or https://github.com/Microsoft/angle/issues/111
Reproduces easily if resize rapidly with change of direction while app is lags below 30 FPS.

Is there are way to workaround this by manually resize SwapChainPanel or set transform for SwapChain outside of ANGLE without modifications to ANGLE itself?

I will try to reproduce this behavior in sample and will update this issue when/if i have minimal working example.

** there is also visual bug (alpha blending?) when panel stop resizing - image became grayish when overlayed with, for example (0,0,0,80)

**Comment by austinkinross** [comment] 2017-05-16 15:56
Hi, thanks for reporting the issue. I'm not aware of any issues in this area (except for the delay during resize), so it would be great to have a sample to reproduce the behavior you're seeing.

Could you also share which Operating System you're running on, and ideally the version number? Thanks a lot!

**Comment by mgrviper** [comment] 2017-05-17 00:37
Some details about OS and project:
I'm running Windows 10, version 1511, build 10586.753.
Project target is 10.0.10240.0, Platform x86

**Comment by mgrviper** [comment] 2017-05-17 02:17
Here is modified sample app in which bug reproducible:
[AngleBugReport123.zip](https://github.com/Microsoft/angle/files/1006326/AngleBugReport123.zip)
How to reproduce:
Resize by dragging topleft corner of window.
When bug manifested cube would became cuboid and background would be white instead of black

Without bug
![withoutbug](https://cloud.githubusercontent.com/assets/22609274/26135715/5122b25a-3af2-11e7-86e5-6eb863eedf46.png)

With bug manifested
![withbug](https://cloud.githubusercontent.com/assets/22609274/26135724/64110cd6-3af2-11e7-8193-a08c2318d537.png)

**Comment by mgrviper** [comment] 2017-05-26 05:33
@austinkinross sorry, can i have any update or confirmation?

**Comment by ToxicAdder** [comment] 2017-07-04 07:31
Having the exact same issue myself: after a while, canvas size stops being updated.

**Comment by JimSEOW** [comment] 2017-07-04 09:12
@austinkinross  We are now looking into how Microsoft Angel for .NET can contribute to a new Page for [WindowsTemplateStudio](https://github.com/Microsoft/WindowsTemplateStudio) to bring Remix3D content from indoor classroom to outdoor mixed reality ( 3D content overlaying live stream video from camera of either a tablet (e.g. WinOnARM Q4 2017) or surface phone (2018) - aligns with Microsoft Global AI integration to classroom for early age children.

It will be synergy to our effort if we could get your support to have an official (.NET c#) Visual Studio Template for Angel's OpenGL ES for XAML.

**Comment by mgrviper** [comment] 2017-09-06 02:54
@austinkinross can you provide some update on this or confirm that this is indeed a bug and would (or wouldn't) be resolved?

**Comment by austinkinross** [comment] 2017-09-08 20:55
Hi, thanks for attaching the repro project and apologies for the delayed reply.

With your repro app, my understanding is that if I drag the top-left corner of the window towards the bottom-right corner, then at some point the cube will become 'stuck' at a fixed-size in the top left-corner of the window on a white background. Is this correct?

If so, then unfortunately I am unable to reproduce the issue. It's possible that this has been fixed in a recent version of Windows, since I am running build 15063 (the Creator's Update, from April 2017) while your build (10586) is from November 2015.

Austin

**Comment by Gavin-Williams** [comment] 2017-10-23 01:57
This issue is now occurring for me as of FCU. SwapChainPanels were resizing in my app just a few days ago. I have rewritten some stuff - but I'm pretty sure the resizing should be automatic with the following code ...
`    <Grid Background="Black">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <SwapChainPanel x:Name="xamlSwapChainPanelA"
                        x:FieldModifier="private" 
                        Grid.Column="0"
                        HorizontalAlignment="Stretch" 
                        VerticalAlignment="Stretch"
                        Width="auto" Height="auto"
                        Margin="24,20,12,20"/>`

**Comment by austinkinross** [comment] 2019-09-20 20:33
Closing out this old issue, since we haven't had any reports of it since 2017.

If you continue to see issues here then I suggest that you ask over on the main ANGLE project's mailing list: https://groups.google.com/forum/#!forum/angleproject

Thanks
Austin

**Closed as completed by austinkinross** 2019-09-20 20:33 UTC
Labels: ms-master
