### ISSUE TITLE
Can't get the timer queries working

### ISSUE THREAD

**Issue by redorav** [microsoft/angle#97] opened 2016-10-05 16:59 UTC
Hi,

I can't seem to get the timer queries working, they always return 0. My code follows the following pattern:

glGenQueriesEXT(1, &m_eventQueries[i]);
glQueryCounterEXT(m_eventQueries[i], GL_TIMESTAMP_EXT);

and then at the end of the frame they're all queried via

glGetQueryObjectui64vEXT(m_eventQueries[i], GL_QUERY_RESULT_EXT, &duration);

where duration is a uint64_t

duration always ends up being 0. I've also checked if the query result is available and the API seems to say it's always available, even if I query it immediately after the call to glQueryCounterEXT.

Am I doing something wrong? I compiled the libraries not too long ago. GL_TIME_ELAPSED_EXT queries are working properly, it's just these that I can't get to work.

The test code seems to suggest they should work, but I can't get them to run because the vcxproj files are not in the repository.

**Comment by austinkinross** [comment] 2016-11-15 19:11
Hi apologies for the delayed response, I completely missed this question! 

Are you still having trouble with timer queries? What hardware are you running this on?

**Comment by redorav** [comment] 2016-11-15 19:28
Hi, I'm running this on an NVIDIA 970 GTX. I could never get them to work properly.

**Comment by austinkinross** [comment] 2016-11-15 22:24
Thanks for the info! 

The spec for EXT_disjoint_timer_query notes this:

> Information about a query target can be queried with the command
> 
> ```
> void GetQueryivEXT(enum target, enum pname, int *params);
> ```
> 
> _target_ identifies the query target and can be TIME_ELAPSED_EXT or
> TIMESTAMP_EXT for timer queries.
> 
> ...
> 
>  If _pname_ is QUERY_COUNTER_BITS_EXT, the implementation-dependent number
>  of bits used to hold the query result for <target> will be placed in
>  _params_.  The number of query counter bits may be zero, in which case
>  the counter contains no useful information.

Have you confirmed that glGetQueryivEXT(GL_TIMESTAMP_EXT, GL_QUERY_COUNTER_BITS_EXT, ...) returns non-zero?

ANGLE has some tests that use these APIs, with the [TimerQueriesTest/Timestamp](https://github.com/Microsoft/angle/blob/54b1fd01f7fddcd7011d5a04e9259edace8a13da/src/tests/gl_tests/TimerQueriesTest.cpp) test following a very similar pattern to the code you described in your first post.  In [recent test runs](https://build.chromium.org/p/tryserver.chromium.angle/builders/win_angle_x64_rel_ng/builds/2690/steps/angle_end2end_tests%20on%20NVIDIA%20GPU%20on%20Windows%20%28with%20patch%29%20on%20Windows-2008ServerR2-SP1/logs/stdio) on NVIDIA, this test has found that glGetQueryivEXT(GL_TIMESTAMP_EXT, GL_QUERY_COUNTER_BITS_EXT, ...) returns zero.

Hope this helps!
Austin

**Comment by austinkinross** [comment] 2016-11-30 21:03
I'm closing out this issue since I believe it's been resolved, but feel free to reactivate it if you have further questions or problems. Thanks!

**Closed as completed by austinkinross** 2016-11-30 21:03 UTC
Labels: question, ms-master
