### ISSUE TITLE
Errors occur when building source from ms-master

### ISSUE THREAD

**Issue by skakraze5** [microsoft/angle#120] opened 2017-04-27 22:03 UTC
When I pull down the source from github and attempt to build the solution, I get build errors. Am I doing something wrong? I managed to work around it by modifying some stuff. But it still seems odd that I would need to.

Steps:
- `git clone git@github.com:Microsoft/angle.git`
-  Open src/angle.sln with Visual Studio
- Build Solution

Errors:
 `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.`

Work around:
- Delete the contents of copy_compiler_dll.bat

System:
Windows 10 Enterprise
Microsoft Visual Studio Enterprise 2015 with Update 3

And what is the state of `build/ANGLE.sln` and `gyp/AGLE.sln`? I like that they include more utilities, tests, and samples. But they too were in a broken state. The test projects were missing and I got compile errors. And I could not find any specific instructions on how to use either of these solutions. So my assumption is that they were broken or just not documented on their intended purpose. Is it broken for others too or again am I just missing something? 

To work around the issue I had to:
- Modify copy_compiler_dll.bat
- Follow the [instructions](https://github.com/google/angle/blob/master/doc/DevSetup.md) from google to setup gclient on my machine  
- Run `python scripts/bootstrap.py` and `glclient sync` to generate the missing test projects
- Remove cpp and header files that were missing from the `translator_lib` project
- Fix a random compile error in src/tests/gl_tests/SixteenBppTextureTest.cpp`
- And even then I still can't compile one of the `texture_loading_dds` examples

So any help or tips to get up and running would be appreciated. 

Commit hash when issue made: https://github.com/Microsoft/angle/commit/f1706c47250db7c9fc47c49c025566ec5974a290

**Comment by austinkinross** [comment] 2017-05-16 16:44
Hi, thanks a lot for opening this issue! Regarding the various issues you mentioned:

> Errors:
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
> 
> Work around:
> 
> Delete the contents of copy_compiler_dll.bat

I'm not able to reproduce this on my PC. Is there anything else in the build log that hints at the cause of the error (e.g. if the compiler DLL doesn't exist)?

Note that this step is to copy D3DCompiler_47.dll from your SDK installation path into your ANGLE build directory, but this isn't necessary on Windows 10 since the compiler is already in system32. As a result, deleting the contents of the .bat file shouldn't affect your build of ANGLE if you're running Windows 10.

> And what is the state of build/ANGLE.sln and gyp/AGLE.sln? I like that they include more utilities, tests, and samples.

Thank you for reporting this! Those projects shouldn't be part of the Microsoft\ANGLE repository. 

> Follow the instructions from google to setup gclient on my machine
> Run python scripts/bootstrap.py and glclient sync to generate the missing test projects
> Remove cpp and header files that were missing from the translator_lib project
> Fix a random compile error in src/tests/gl_tests/SixteenBppTextureTest.cpp`

On Microsoft\ANGLE, we're focused on generating great ANGLE binaries to be consumed by Windows Store and/or desktop applications. There are some other projects included in ANGLE (e.g. the desktop win32 tests) that we don't maintain over here, since we don't expect Microsoft\ANGLE users to typically use them. If you're interested in running the desktop ANGLE tests then I strongly recommend using Google's master version of ANGLE.

> And even then I still can't compile one of the texture_loading_dds examples

I see the same build error when building /samples/samples.sln, We'll try to fix this soon.

Thanks again for opening this issue!
Austin

**Comment by austinkinross** [comment] 2017-05-31 17:35
Hi, we just pushed a fix to ms-master for the build problems listed above. If you hit the D3DCompiler_47.dll issue again then feel free to reactivate this issue. Thanks again!

**Closed as completed by austinkinross** 2017-05-31 17:35 UTC
Labels: bug, ms-master
